// Generated by project-context @@PACKAGE_VERSION@@.
import { spawnSync } from "node:child_process";
const PY=@@PYTHON@@; const CTX=@@CTX@@;
function run(args, input, cwd) { const r=spawnSync(PY,[CTX,...args],{input:JSON.stringify(input||{}),encoding:"utf8",cwd}); return (r.stdout||"").trim(); }
function sid(event) { return event?.properties?.info?.id || event?.properties?.sessionID || event?.properties?.sessionId || "opencode-runtime"; }
export const ProjectContextPlugin = async ({ directory, worktree }) => ({
  event: async ({event}) => {
    const base={cwd:worktree||directory,session_id:sid(event)};
    if(event.type==="session.created") run(["hook","session-start","--host","opencode"],base,directory);
    if(event.type==="session.idle") run(["hook","stop","--host","opencode"],base,directory);
    if(event.type==="session.compacted") run(["hook","compact-after","--host","opencode"],base,directory);
    if(event.type==="session.deleted") run(["hook","session-end","--host","opencode"],base,directory);
  },
  "experimental.session.compacting": async (input, output) => {
    run(["hook","compact-before","--host","opencode"],{cwd:worktree||directory,session_id:input?.sessionID||"opencode-runtime"},directory);
    const r=spawnSync(PY,[CTX,"--cwd",worktree||directory,"startup","--compact"],{encoding:"utf8",cwd:directory});
    if(r.status===0 && r.stdout.trim()) output.context.push(r.stdout.trim());
  }
});
