// Generated by project-context @@PACKAGE_VERSION@@.
import { spawnSync } from "node:child_process";
export default function projectContext(pi) {
  const PY=@@PYTHON@@, CTX=@@CTX@@; let sessionId=`pi-${Date.now()}-${Math.random().toString(16).slice(2)}`; let injected=false;
  const run=(event,data,cwd)=>spawnSync(PY,[CTX,"hook",event,"--host","pi"],{input:JSON.stringify({cwd,session_id:sessionId,...data}),encoding:"utf8",cwd});
  const startup=(cwd)=>spawnSync(PY,[CTX,"--cwd",cwd,"startup"],{encoding:"utf8",cwd});
  pi.on("session_start", async (event, c) => { sessionId=c.sessionManager.getSessionFile?.() || sessionId; run("session-start",{source:event.reason},c.cwd); injected=false; });
  pi.on("before_agent_start", async (_event, c) => {
    run("turn-start",{},c.cwd);
    if(!injected) { const r=startup(c.cwd); injected=true; if(r.status===0 && r.stdout.trim()) return {message:{customType:"project-context",content:r.stdout.trim(),display:false}}; }
  });
  pi.on("session_before_compact", async (_event,c)=>{ run("compact-before",{},c.cwd); });
  pi.on("session_compact", async (_event,c)=>{ run("compact-after",{},c.cwd); injected=false; });
  pi.on("agent_settled", async (_event,c)=>{ run("stop",{},c.cwd); });
  pi.on("session_shutdown", async (_event,c)=>{ run("session-end",{},c.cwd); });
}
